<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-KD6JVA8H" failures="0" tests="3" name="Intervidw.TestClass_ExceptionHandling" time="0.019" errors="0" timestamp="2025-01-02T21:30:42 IST" skipped="2">
  <testcase classname="Intervidw.TestClass_ExceptionHandling" name="CustomizedException" time="0.019"/>
  <testcase classname="Intervidw.TestClass_ExceptionHandling" name="ExceptionHandledinCatchBlock">
    <skipped/>
  </testcase> <!-- ExceptionHandledinCatchBlock -->
  <testcase classname="Intervidw.TestClass_ExceptionHandling" name="ManuallyThrowException">
    <skipped/>
  </testcase> <!-- ManuallyThrowException -->
</testsuite> <!-- Intervidw.TestClass_ExceptionHandling -->
